# Generated by Django 3.2.3 on 2021-05-30 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(max_length=512, unique=True)),
                ('type', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='TextStringRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(unique=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_string_child', to='text_strings.textstring')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_string_parent', to='text_strings.textstring')),
            ],
        ),
    ]
