# Generated by Django 3.2.3 on 2021-05-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_strings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textstringrelation',
            name='order',
            field=models.IntegerField(),
        ),
    ]
