# Generated by Django 3.2.3 on 2021-05-30 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('text_strings', '0002_alter_textstringrelation_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textstringrelation',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t_s_tr_child', to='text_strings.textstring'),
        ),
        migrations.AlterField(
            model_name='textstringrelation',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t_s_tr_parent', to='text_strings.textstring'),
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t_s_k_document', to='text_strings.textstring')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t_s_k_keyword', to='text_strings.textstring')),
            ],
        ),
    ]
