# Generated by Django 3.2.3 on 2021-05-30 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('text_strings', '0003_auto_20210530_1334'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Keyword',
            new_name='DocumentKeyword',
        ),
        migrations.CreateModel(
            name='UserScoringToDocumentKeywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=512)),
                ('is_keyword', models.BooleanField()),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text_strings.documentkeyword')),
            ],
        ),
    ]
