# Generated by Django 3.2.3 on 2021-05-31 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_strings', '0004_auto_20210530_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentkeyword',
            name='_is_keyword',
            field=models.BooleanField(default=True),
        ),
    ]
