# Generated by Django 3.2.3 on 2021-05-22 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='texts.word')),
            ],
        ),
        migrations.CreateModel(
            name='StopWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='texts.word')),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.ManyToManyField(to='texts.KeyWord')),
                ('stopwords', models.ManyToManyField(to='texts.StopWord')),
                ('topics', models.ManyToManyField(to='texts.Topic')),
                ('words', models.ManyToManyField(to='texts.Word')),
            ],
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.ManyToManyField(to='texts.KeyWord')),
                ('sentences', models.ManyToManyField(to='texts.Sentence')),
                ('stopwords', models.ManyToManyField(to='texts.StopWord')),
                ('topics', models.ManyToManyField(to='texts.Topic')),
            ],
        ),
        migrations.AddField(
            model_name='keyword',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='texts.word'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.ManyToManyField(to='texts.KeyWord')),
                ('paragraphs', models.ManyToManyField(to='texts.Paragraph')),
                ('stopwords', models.ManyToManyField(to='texts.StopWord')),
                ('topics', models.ManyToManyField(to='texts.Topic')),
            ],
        ),
        migrations.CreateModel(
            name='Corpus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documents', models.ManyToManyField(to='texts.Document')),
                ('keywords', models.ManyToManyField(to='texts.KeyWord')),
                ('stopwords', models.ManyToManyField(to='texts.StopWord')),
                ('topics', models.ManyToManyField(to='texts.Topic')),
            ],
        ),
    ]
