# Generated by Django 3.2.3 on 2021-05-22 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturesWordSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_stop_word', models.BooleanField(null=True)),
                ('is_key_word', models.BooleanField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='document',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='document',
            name='paragraphs',
        ),
        migrations.RemoveField(
            model_name='document',
            name='stopwords',
        ),
        migrations.RemoveField(
            model_name='document',
            name='topics',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='word',
        ),
        migrations.RemoveField(
            model_name='paragraph',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='paragraph',
            name='sentences',
        ),
        migrations.RemoveField(
            model_name='paragraph',
            name='stopwords',
        ),
        migrations.RemoveField(
            model_name='paragraph',
            name='topics',
        ),
        migrations.RemoveField(
            model_name='stopword',
            name='word',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='word',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='char',
            new_name='string',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='stopwords',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='topics',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='words',
        ),
        migrations.DeleteModel(
            name='Corpus',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='KeyWord',
        ),
        migrations.DeleteModel(
            name='Paragraph',
        ),
        migrations.DeleteModel(
            name='StopWord',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.AddField(
            model_name='featureswordsentence',
            name='next_word',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_fws_next_word', to='texts.word'),
        ),
        migrations.AddField(
            model_name='featureswordsentence',
            name='previous_word',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_fws_previous_word', to='texts.word'),
        ),
        migrations.AddField(
            model_name='featureswordsentence',
            name='sentence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='texts.sentence'),
        ),
        migrations.AddField(
            model_name='featureswordsentence',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t_fws_word', to='texts.word'),
        ),
    ]
