# Generated by Django 3.2.3 on 2021-05-22 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0002_auto_20210522_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureswordsentence',
            name='is_key_word',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='featureswordsentence',
            name='is_stop_word',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='featureswordsentence',
            name='next_word',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_fws_next_word', to='texts.word'),
        ),
        migrations.AlterField(
            model_name='featureswordsentence',
            name='previous_word',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_fws_previous_word', to='texts.word'),
        ),
    ]
