# Generated by Django 3.2.3 on 2021-05-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0003_auto_20210522_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureswordsentence',
            name='is_key_word',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='featureswordsentence',
            name='is_stop_word',
            field=models.BooleanField(default=False),
        ),
    ]
