# Generated by Django 3.2.3 on 2021-05-22 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0004_auto_20210522_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Corpus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes', models.ManyToManyField(to='texts.Class')),
                ('stop_words', models.ManyToManyField(related_name='t_c_stop_words', to='texts.Word')),
                ('symbols', models.ManyToManyField(related_name='t_c_stop_symbols', to='texts.Word')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_words', models.ManyToManyField(to='texts.Word')),
            ],
        ),
        migrations.RemoveField(
            model_name='featureswordsentence',
            name='is_key_word',
        ),
        migrations.RemoveField(
            model_name='featureswordsentence',
            name='is_stop_word',
        ),
        migrations.CreateModel(
            name='FeaturesSentenceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='texts.document')),
                ('index_word_sentence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='texts.word')),
                ('next_sentence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_fsd_next_sentence', to='texts.sentence')),
                ('previous_sentence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_fsd_previous_sentence', to='texts.sentence')),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t_fsd_sentence', to='texts.sentence')),
            ],
        ),
        migrations.CreateModel(
            name='FeaturesDocumentCorpus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='texts.corpus')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='texts.document')),
            ],
        ),
    ]
