# Generated by Django 3.2.3 on 2021-05-24 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0005_auto_20210522_1415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corpus',
            options={'verbose_name': 'Corpus', 'verbose_name_plural': 'Corpus'},
        ),
    ]
